name: Build

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: '8.11'

      - name: Build with Gradle
        run: gradle build

      - name: Upload Artifact (Fabric)
        uses: actions/upload-artifact@v4
        with:
          name: fabric
          path: fabric/build/libs/*.jar

      - name: Upload Artifact (NeoForge)
        uses: actions/upload-artifact@v4
        with:
          name: neoforge
          path: neoforge/build/libs/*.jar

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gh release create ${{github.ref_name}} --generate-notes fabric/build/libs/*.jar neoforge/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
